export enum ContactsActionTypes {
  LOADING = "CONTACTS/LOADING",
  FETCH_SUCCESS = "CONTACTS/FETCH_SUCCESS",
  FETCH_ERROR = "CONTACTS/FETCH_ERROR",
  ADD_SUCCESS = "CONTACTS/ADD_SUCCESS",
  UPDATE_SUCCESS = "CONTACTS/UPDATE_SUCCESS",
  DELETE_SUCCESS = "CONTACTS/DELETE_SUCCESS",
}
