export enum ContactsTableActionTypes {
  SEARCH_LOADING = "CONTACTS_TABLE/SEARCH_LOADING",
  SEARCH_SUCCESS = "CONTACTS_TABLE/SEARCH_SUCCESS",
  SEARCH_ERROR = "CONTACTS_TABLE/SEARCH_ERROR",
  CLEAR_SEARCH = "CONTACTS_TABLE/CLEAR_SEARCH",
}
