export enum SelectContactsActionTypes {
  SELECT = "CONTACTS/SELECT",
  CLEAR_SELECTION = "CONTACTS/CLEAR_SELECTION",
  FETCH_LOADING = "CONTACTS/FETCH_SELECTED_LOADING",
  FETCH_SUCCESS = "CONTACTS/FETCH_SELECTED_SUCCESS",
  FETCH_ERROR = "CONTACTS/FETCH_SELECTED_ERROR",
}
