export enum ActivitiesTableActionTypes {
  SEARCH_LOADING = "ACTIVITIES_TABLE/SEARCH_LOADING",
  SEARCH_SUCCESS = "ACTIVITIES_TABLE/SEARCH_SUCCESS",
  SEARCH_ERROR = "ACTIVITIES_TABLE/SEARCH_ERROR",
  CLEAR_SEARCH = "ACTIVITIES_TABLE/CLEAR_SEARCH",
}
